FROM postgres:16-alpine

# Set default environment variables
ENV POSTGRES_USER=allocation_user
ENV POSTGRES_PASSWORD=allocation_pass
ENV POSTGRES_DB=allocation_db

# Expose PostgreSQL port
EXPOSE 5432

CMD ["postgres"]