// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation_labels.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkConversationLabelExists = `-- name: CheckConversationLabelExists :one
SELECT EXISTS(
    SELECT 1 FROM conversation_labels 
    WHERE conversation_id = $1 AND label_id = $2
) AS exists
`

type CheckConversationLabelExistsParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	LabelID        pgtype.UUID `json:"label_id"`
}

func (q *Queries) CheckConversationLabelExists(ctx context.Context, arg CheckConversationLabelExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkConversationLabelExists, arg.ConversationID, arg.LabelID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createConversationLabel = `-- name: CreateConversationLabel :exec
INSERT INTO conversation_labels (id, conversation_id, label_id, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateConversationLabelParams struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	LabelID        pgtype.UUID        `json:"label_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateConversationLabel(ctx context.Context, arg CreateConversationLabelParams) error {
	_, err := q.db.Exec(ctx, createConversationLabel,
		arg.ID,
		arg.ConversationID,
		arg.LabelID,
		arg.CreatedAt,
	)
	return err
}

const deleteAllConversationLabels = `-- name: DeleteAllConversationLabels :exec
DELETE FROM conversation_labels WHERE conversation_id = $1
`

func (q *Queries) DeleteAllConversationLabels(ctx context.Context, conversationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllConversationLabels, conversationID)
	return err
}

const deleteConversationLabel = `-- name: DeleteConversationLabel :exec
DELETE FROM conversation_labels WHERE conversation_id = $1 AND label_id = $2
`

type DeleteConversationLabelParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	LabelID        pgtype.UUID `json:"label_id"`
}

func (q *Queries) DeleteConversationLabel(ctx context.Context, arg DeleteConversationLabelParams) error {
	_, err := q.db.Exec(ctx, deleteConversationLabel, arg.ConversationID, arg.LabelID)
	return err
}

const getConversationLabelsByConversationID = `-- name: GetConversationLabelsByConversationID :many
SELECT id, conversation_id, label_id, created_at FROM conversation_labels WHERE conversation_id = $1
`

func (q *Queries) GetConversationLabelsByConversationID(ctx context.Context, conversationID pgtype.UUID) ([]ConversationLabel, error) {
	rows, err := q.db.Query(ctx, getConversationLabelsByConversationID, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationLabel{}
	for rows.Next() {
		var i ConversationLabel
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.LabelID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationLabelsByLabelID = `-- name: GetConversationLabelsByLabelID :many
SELECT id, conversation_id, label_id, created_at FROM conversation_labels WHERE label_id = $1
`

func (q *Queries) GetConversationLabelsByLabelID(ctx context.Context, labelID pgtype.UUID) ([]ConversationLabel, error) {
	rows, err := q.db.Query(ctx, getConversationLabelsByLabelID, labelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConversationLabel{}
	for rows.Next() {
		var i ConversationLabel
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.LabelID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
