// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: grace_period_assignments.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGracePeriodAssignment = `-- name: CreateGracePeriodAssignment :exec
INSERT INTO grace_period_assignments (id, conversation_id, operator_id, expires_at, reason, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateGracePeriodAssignmentParams struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	OperatorID     pgtype.UUID        `json:"operator_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	Reason         GracePeriodReason  `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateGracePeriodAssignment(ctx context.Context, arg CreateGracePeriodAssignmentParams) error {
	_, err := q.db.Exec(ctx, createGracePeriodAssignment,
		arg.ID,
		arg.ConversationID,
		arg.OperatorID,
		arg.ExpiresAt,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}

const deleteGracePeriodAssignment = `-- name: DeleteGracePeriodAssignment :exec
DELETE FROM grace_period_assignments WHERE id = $1
`

func (q *Queries) DeleteGracePeriodAssignment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGracePeriodAssignment, id)
	return err
}

const deleteGracePeriodByConversationID = `-- name: DeleteGracePeriodByConversationID :exec
DELETE FROM grace_period_assignments WHERE conversation_id = $1
`

func (q *Queries) DeleteGracePeriodByConversationID(ctx context.Context, conversationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGracePeriodByConversationID, conversationID)
	return err
}

const deleteGracePeriodsByOperatorID = `-- name: DeleteGracePeriodsByOperatorID :exec
DELETE FROM grace_period_assignments WHERE operator_id = $1
`

func (q *Queries) DeleteGracePeriodsByOperatorID(ctx context.Context, operatorID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGracePeriodsByOperatorID, operatorID)
	return err
}

const getAndLockExpiredGracePeriods = `-- name: GetAndLockExpiredGracePeriods :many
SELECT id, conversation_id, operator_id, expires_at, reason, created_at FROM grace_period_assignments
WHERE expires_at <= NOW()
ORDER BY expires_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// CRITICAL: Get and lock expired for worker
func (q *Queries) GetAndLockExpiredGracePeriods(ctx context.Context, limit int32) ([]GracePeriodAssignment, error) {
	rows, err := q.db.Query(ctx, getAndLockExpiredGracePeriods, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GracePeriodAssignment{}
	for rows.Next() {
		var i GracePeriodAssignment
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.OperatorID,
			&i.ExpiresAt,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredGracePeriods = `-- name: GetExpiredGracePeriods :many
SELECT id, conversation_id, operator_id, expires_at, reason, created_at FROM grace_period_assignments
WHERE expires_at <= NOW()
ORDER BY expires_at ASC
LIMIT $1
`

func (q *Queries) GetExpiredGracePeriods(ctx context.Context, limit int32) ([]GracePeriodAssignment, error) {
	rows, err := q.db.Query(ctx, getExpiredGracePeriods, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GracePeriodAssignment{}
	for rows.Next() {
		var i GracePeriodAssignment
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.OperatorID,
			&i.ExpiresAt,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGracePeriodByConversationID = `-- name: GetGracePeriodByConversationID :one
SELECT id, conversation_id, operator_id, expires_at, reason, created_at FROM grace_period_assignments WHERE conversation_id = $1
`

func (q *Queries) GetGracePeriodByConversationID(ctx context.Context, conversationID pgtype.UUID) (GracePeriodAssignment, error) {
	row := q.db.QueryRow(ctx, getGracePeriodByConversationID, conversationID)
	var i GracePeriodAssignment
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.OperatorID,
		&i.ExpiresAt,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getGracePeriodsByOperatorID = `-- name: GetGracePeriodsByOperatorID :many
SELECT id, conversation_id, operator_id, expires_at, reason, created_at FROM grace_period_assignments WHERE operator_id = $1
`

func (q *Queries) GetGracePeriodsByOperatorID(ctx context.Context, operatorID pgtype.UUID) ([]GracePeriodAssignment, error) {
	rows, err := q.db.Query(ctx, getGracePeriodsByOperatorID, operatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GracePeriodAssignment{}
	for rows.Next() {
		var i GracePeriodAssignment
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.OperatorID,
			&i.ExpiresAt,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
