// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIdempotencyKeys = `-- name: CountIdempotencyKeys :one
SELECT COUNT(*) FROM idempotency_keys WHERE tenant_id = $1
`

func (q *Queries) CountIdempotencyKeys(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIdempotencyKeys, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIdempotencyKey = `-- name: CreateIdempotencyKey :exec
INSERT INTO idempotency_keys (
    id, key, tenant_id, endpoint, method, request_hash,
    response_status, response_body, created_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateIdempotencyKeyParams struct {
	ID             pgtype.UUID        `json:"id"`
	Key            string             `json:"key"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Endpoint       string             `json:"endpoint"`
	Method         string             `json:"method"`
	RequestHash    pgtype.Text        `json:"request_hash"`
	ResponseStatus int32              `json:"response_status"`
	ResponseBody   []byte             `json:"response_body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, createIdempotencyKey,
		arg.ID,
		arg.Key,
		arg.TenantID,
		arg.Endpoint,
		arg.Method,
		arg.RequestHash,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :exec
DELETE FROM idempotency_keys WHERE id = $1
`

func (q *Queries) DeleteIdempotencyKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteIdempotencyKey, id)
	return err
}

const getExpiredIdempotencyKeysForCleanup = `-- name: GetExpiredIdempotencyKeysForCleanup :many
SELECT id, key, tenant_id, endpoint, method, request_hash, response_status, response_body, created_at, expires_at FROM idempotency_keys
WHERE expires_at < NOW()
ORDER BY expires_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetExpiredIdempotencyKeysForCleanup(ctx context.Context, limit int32) ([]IdempotencyKey, error) {
	rows, err := q.db.Query(ctx, getExpiredIdempotencyKeysForCleanup, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdempotencyKey{}
	for rows.Next() {
		var i IdempotencyKey
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.TenantID,
			&i.Endpoint,
			&i.Method,
			&i.RequestHash,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, key, tenant_id, endpoint, method, request_hash, response_status, response_body, created_at, expires_at FROM idempotency_keys
WHERE tenant_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Key      string      `json:"key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.TenantID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.TenantID,
		&i.Endpoint,
		&i.Method,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
