// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inboxes.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInbox = `-- name: CreateInbox :exec
INSERT INTO inboxes (id, tenant_id, phone_number, display_name, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateInboxParams struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	PhoneNumber string             `json:"phone_number"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateInbox(ctx context.Context, arg CreateInboxParams) error {
	_, err := q.db.Exec(ctx, createInbox,
		arg.ID,
		arg.TenantID,
		arg.PhoneNumber,
		arg.DisplayName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteInbox = `-- name: DeleteInbox :exec
DELETE FROM inboxes WHERE id = $1
`

func (q *Queries) DeleteInbox(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInbox, id)
	return err
}

const getInboxByID = `-- name: GetInboxByID :one
SELECT id, tenant_id, phone_number, display_name, created_at, updated_at FROM inboxes WHERE id = $1
`

func (q *Queries) GetInboxByID(ctx context.Context, id pgtype.UUID) (Inbox, error) {
	row := q.db.QueryRow(ctx, getInboxByID, id)
	var i Inbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneNumber,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInboxByPhoneNumber = `-- name: GetInboxByPhoneNumber :one
SELECT id, tenant_id, phone_number, display_name, created_at, updated_at FROM inboxes WHERE tenant_id = $1 AND phone_number = $2
`

type GetInboxByPhoneNumberParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	PhoneNumber string      `json:"phone_number"`
}

func (q *Queries) GetInboxByPhoneNumber(ctx context.Context, arg GetInboxByPhoneNumberParams) (Inbox, error) {
	row := q.db.QueryRow(ctx, getInboxByPhoneNumber, arg.TenantID, arg.PhoneNumber)
	var i Inbox
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PhoneNumber,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInboxesByTenantID = `-- name: GetInboxesByTenantID :many
SELECT id, tenant_id, phone_number, display_name, created_at, updated_at FROM inboxes WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetInboxesByTenantID(ctx context.Context, tenantID pgtype.UUID) ([]Inbox, error) {
	rows, err := q.db.Query(ctx, getInboxesByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inbox{}
	for rows.Next() {
		var i Inbox
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PhoneNumber,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInbox = `-- name: UpdateInbox :exec
UPDATE inboxes
SET phone_number = $2,
    display_name = $3,
    updated_at = $4
WHERE id = $1
`

type UpdateInboxParams struct {
	ID          pgtype.UUID        `json:"id"`
	PhoneNumber string             `json:"phone_number"`
	DisplayName string             `json:"display_name"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateInbox(ctx context.Context, arg UpdateInboxParams) error {
	_, err := q.db.Exec(ctx, updateInbox,
		arg.ID,
		arg.PhoneNumber,
		arg.DisplayName,
		arg.UpdatedAt,
	)
	return err
}
