// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: labels.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLabel = `-- name: CreateLabel :exec
INSERT INTO labels (id, tenant_id, inbox_id, name, color, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateLabelParams struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	InboxID   pgtype.UUID        `json:"inbox_id"`
	Name      string             `json:"name"`
	Color     pgtype.Text        `json:"color"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) error {
	_, err := q.db.Exec(ctx, createLabel,
		arg.ID,
		arg.TenantID,
		arg.InboxID,
		arg.Name,
		arg.Color,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const deleteLabel = `-- name: DeleteLabel :exec
DELETE FROM labels WHERE id = $1
`

func (q *Queries) DeleteLabel(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLabel, id)
	return err
}

const getLabelByID = `-- name: GetLabelByID :one
SELECT id, tenant_id, inbox_id, name, color, created_by, created_at FROM labels WHERE id = $1
`

func (q *Queries) GetLabelByID(ctx context.Context, id pgtype.UUID) (Label, error) {
	row := q.db.QueryRow(ctx, getLabelByID, id)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InboxID,
		&i.Name,
		&i.Color,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getLabelByName = `-- name: GetLabelByName :one
SELECT id, tenant_id, inbox_id, name, color, created_by, created_at FROM labels WHERE inbox_id = $1 AND name = $2
`

type GetLabelByNameParams struct {
	InboxID pgtype.UUID `json:"inbox_id"`
	Name    string      `json:"name"`
}

func (q *Queries) GetLabelByName(ctx context.Context, arg GetLabelByNameParams) (Label, error) {
	row := q.db.QueryRow(ctx, getLabelByName, arg.InboxID, arg.Name)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InboxID,
		&i.Name,
		&i.Color,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getLabelsByInboxID = `-- name: GetLabelsByInboxID :many
SELECT id, tenant_id, inbox_id, name, color, created_by, created_at FROM labels WHERE tenant_id = $1 AND inbox_id = $2 ORDER BY name
`

type GetLabelsByInboxIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	InboxID  pgtype.UUID `json:"inbox_id"`
}

func (q *Queries) GetLabelsByInboxID(ctx context.Context, arg GetLabelsByInboxIDParams) ([]Label, error) {
	rows, err := q.db.Query(ctx, getLabelsByInboxID, arg.TenantID, arg.InboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InboxID,
			&i.Name,
			&i.Color,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLabel = `-- name: UpdateLabel :exec
UPDATE labels
SET name = $2,
    color = $3
WHERE id = $1
`

type UpdateLabelParams struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Color pgtype.Text `json:"color"`
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) error {
	_, err := q.db.Exec(ctx, updateLabel, arg.ID, arg.Name, arg.Color)
	return err
}
