// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ConversationState string

const (
	ConversationStateQUEUED    ConversationState = "QUEUED"
	ConversationStateALLOCATED ConversationState = "ALLOCATED"
	ConversationStateRESOLVED  ConversationState = "RESOLVED"
)

func (e *ConversationState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConversationState(s)
	case string:
		*e = ConversationState(s)
	default:
		return fmt.Errorf("unsupported scan type for ConversationState: %T", src)
	}
	return nil
}

type NullConversationState struct {
	ConversationState ConversationState `json:"conversation_state"`
	Valid             bool              `json:"valid"` // Valid is true if ConversationState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConversationState) Scan(value interface{}) error {
	if value == nil {
		ns.ConversationState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConversationState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConversationState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConversationState), nil
}

type GracePeriodReason string

const (
	GracePeriodReasonOFFLINE GracePeriodReason = "OFFLINE"
	GracePeriodReasonMANUAL  GracePeriodReason = "MANUAL"
)

func (e *GracePeriodReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GracePeriodReason(s)
	case string:
		*e = GracePeriodReason(s)
	default:
		return fmt.Errorf("unsupported scan type for GracePeriodReason: %T", src)
	}
	return nil
}

type NullGracePeriodReason struct {
	GracePeriodReason GracePeriodReason `json:"grace_period_reason"`
	Valid             bool              `json:"valid"` // Valid is true if GracePeriodReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGracePeriodReason) Scan(value interface{}) error {
	if value == nil {
		ns.GracePeriodReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GracePeriodReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGracePeriodReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GracePeriodReason), nil
}

type OperatorRole string

const (
	OperatorRoleOPERATOR OperatorRole = "OPERATOR"
	OperatorRoleMANAGER  OperatorRole = "MANAGER"
	OperatorRoleADMIN    OperatorRole = "ADMIN"
)

func (e *OperatorRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OperatorRole(s)
	case string:
		*e = OperatorRole(s)
	default:
		return fmt.Errorf("unsupported scan type for OperatorRole: %T", src)
	}
	return nil
}

type NullOperatorRole struct {
	OperatorRole OperatorRole `json:"operator_role"`
	Valid        bool         `json:"valid"` // Valid is true if OperatorRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOperatorRole) Scan(value interface{}) error {
	if value == nil {
		ns.OperatorRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OperatorRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOperatorRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OperatorRole), nil
}

type OperatorStatusType string

const (
	OperatorStatusTypeAVAILABLE OperatorStatusType = "AVAILABLE"
	OperatorStatusTypeOFFLINE   OperatorStatusType = "OFFLINE"
)

func (e *OperatorStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OperatorStatusType(s)
	case string:
		*e = OperatorStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for OperatorStatusType: %T", src)
	}
	return nil
}

type NullOperatorStatusType struct {
	OperatorStatusType OperatorStatusType `json:"operator_status_type"`
	Valid              bool               `json:"valid"` // Valid is true if OperatorStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOperatorStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.OperatorStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OperatorStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOperatorStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OperatorStatusType), nil
}

type ConversationLabel struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	LabelID        pgtype.UUID        `json:"label_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ConversationRef struct {
	ID                     pgtype.UUID        `json:"id"`
	TenantID               pgtype.UUID        `json:"tenant_id"`
	InboxID                pgtype.UUID        `json:"inbox_id"`
	ExternalConversationID string             `json:"external_conversation_id"`
	CustomerPhoneNumber    string             `json:"customer_phone_number"`
	State                  ConversationState  `json:"state"`
	AssignedOperatorID     pgtype.UUID        `json:"assigned_operator_id"`
	LastMessageAt          pgtype.Timestamptz `json:"last_message_at"`
	MessageCount           int32              `json:"message_count"`
	PriorityScore          pgtype.Numeric     `json:"priority_score"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	ResolvedAt             pgtype.Timestamptz `json:"resolved_at"`
}

type GracePeriodAssignment struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	OperatorID     pgtype.UUID        `json:"operator_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	Reason         GracePeriodReason  `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// Stores idempotency keys with cached responses for deduplication
type IdempotencyKey struct {
	ID pgtype.UUID `json:"id"`
	// Client-provided idempotency key (UUID recommended)
	Key      string      `json:"key"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Endpoint string      `json:"endpoint"`
	Method   string      `json:"method"`
	// SHA256 hash of request body for validation (optional)
	RequestHash pgtype.Text `json:"request_hash"`
	// HTTP status code of the original response
	ResponseStatus int32 `json:"response_status"`
	// Full JSON response body
	ResponseBody []byte             `json:"response_body"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	// When this record can be cleaned up
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Inbox struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	PhoneNumber string             `json:"phone_number"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Label struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	InboxID   pgtype.UUID        `json:"inbox_id"`
	Name      string             `json:"name"`
	Color     pgtype.Text        `json:"color"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Operator struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Role      OperatorRole       `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OperatorInboxSubscription struct {
	ID         pgtype.UUID        `json:"id"`
	OperatorID pgtype.UUID        `json:"operator_id"`
	InboxID    pgtype.UUID        `json:"inbox_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type OperatorStatus struct {
	ID                 pgtype.UUID        `json:"id"`
	OperatorID         pgtype.UUID        `json:"operator_id"`
	Status             OperatorStatusType `json:"status"`
	LastStatusChangeAt pgtype.Timestamptz `json:"last_status_change_at"`
}

type Tenant struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	PriorityWeightAlpha pgtype.Numeric     `json:"priority_weight_alpha"`
	PriorityWeightBeta  pgtype.Numeric     `json:"priority_weight_beta"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy           pgtype.UUID        `json:"updated_by"`
}
