// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operator_inbox_subscriptions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkSubscriptionExists = `-- name: CheckSubscriptionExists :one
SELECT EXISTS(
    SELECT 1 FROM operator_inbox_subscriptions 
    WHERE operator_id = $1 AND inbox_id = $2
) AS exists
`

type CheckSubscriptionExistsParams struct {
	OperatorID pgtype.UUID `json:"operator_id"`
	InboxID    pgtype.UUID `json:"inbox_id"`
}

func (q *Queries) CheckSubscriptionExists(ctx context.Context, arg CheckSubscriptionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkSubscriptionExists, arg.OperatorID, arg.InboxID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createSubscription = `-- name: CreateSubscription :exec
INSERT INTO operator_inbox_subscriptions (id, operator_id, inbox_id, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateSubscriptionParams struct {
	ID         pgtype.UUID        `json:"id"`
	OperatorID pgtype.UUID        `json:"operator_id"`
	InboxID    pgtype.UUID        `json:"inbox_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createSubscription,
		arg.ID,
		arg.OperatorID,
		arg.InboxID,
		arg.CreatedAt,
	)
	return err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM operator_inbox_subscriptions WHERE id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubscription, id)
	return err
}

const deleteSubscriptionByOperatorAndInbox = `-- name: DeleteSubscriptionByOperatorAndInbox :exec
DELETE FROM operator_inbox_subscriptions 
WHERE operator_id = $1 AND inbox_id = $2
`

type DeleteSubscriptionByOperatorAndInboxParams struct {
	OperatorID pgtype.UUID `json:"operator_id"`
	InboxID    pgtype.UUID `json:"inbox_id"`
}

func (q *Queries) DeleteSubscriptionByOperatorAndInbox(ctx context.Context, arg DeleteSubscriptionByOperatorAndInboxParams) error {
	_, err := q.db.Exec(ctx, deleteSubscriptionByOperatorAndInbox, arg.OperatorID, arg.InboxID)
	return err
}

const getSubscribedInboxIDs = `-- name: GetSubscribedInboxIDs :many
SELECT inbox_id FROM operator_inbox_subscriptions WHERE operator_id = $1
`

func (q *Queries) GetSubscribedInboxIDs(ctx context.Context, operatorID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getSubscribedInboxIDs, operatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var inbox_id pgtype.UUID
		if err := rows.Scan(&inbox_id); err != nil {
			return nil, err
		}
		items = append(items, inbox_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, operator_id, inbox_id, created_at FROM operator_inbox_subscriptions WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id pgtype.UUID) (OperatorInboxSubscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i OperatorInboxSubscription
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.InboxID,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionByOperatorAndInbox = `-- name: GetSubscriptionByOperatorAndInbox :one
SELECT id, operator_id, inbox_id, created_at FROM operator_inbox_subscriptions 
WHERE operator_id = $1 AND inbox_id = $2
`

type GetSubscriptionByOperatorAndInboxParams struct {
	OperatorID pgtype.UUID `json:"operator_id"`
	InboxID    pgtype.UUID `json:"inbox_id"`
}

func (q *Queries) GetSubscriptionByOperatorAndInbox(ctx context.Context, arg GetSubscriptionByOperatorAndInboxParams) (OperatorInboxSubscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByOperatorAndInbox, arg.OperatorID, arg.InboxID)
	var i OperatorInboxSubscription
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.InboxID,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionsByInboxID = `-- name: GetSubscriptionsByInboxID :many
SELECT id, operator_id, inbox_id, created_at FROM operator_inbox_subscriptions WHERE inbox_id = $1
`

func (q *Queries) GetSubscriptionsByInboxID(ctx context.Context, inboxID pgtype.UUID) ([]OperatorInboxSubscription, error) {
	rows, err := q.db.Query(ctx, getSubscriptionsByInboxID, inboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperatorInboxSubscription{}
	for rows.Next() {
		var i OperatorInboxSubscription
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.InboxID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionsByOperatorID = `-- name: GetSubscriptionsByOperatorID :many
SELECT id, operator_id, inbox_id, created_at FROM operator_inbox_subscriptions WHERE operator_id = $1
`

func (q *Queries) GetSubscriptionsByOperatorID(ctx context.Context, operatorID pgtype.UUID) ([]OperatorInboxSubscription, error) {
	rows, err := q.db.Query(ctx, getSubscriptionsByOperatorID, operatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperatorInboxSubscription{}
	for rows.Next() {
		var i OperatorInboxSubscription
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.InboxID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
