// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operator_status.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOperatorStatus = `-- name: CreateOperatorStatus :exec
INSERT INTO operator_status (id, operator_id, status, last_status_change_at)
VALUES ($1, $2, $3, $4)
`

type CreateOperatorStatusParams struct {
	ID                 pgtype.UUID        `json:"id"`
	OperatorID         pgtype.UUID        `json:"operator_id"`
	Status             OperatorStatusType `json:"status"`
	LastStatusChangeAt pgtype.Timestamptz `json:"last_status_change_at"`
}

func (q *Queries) CreateOperatorStatus(ctx context.Context, arg CreateOperatorStatusParams) error {
	_, err := q.db.Exec(ctx, createOperatorStatus,
		arg.ID,
		arg.OperatorID,
		arg.Status,
		arg.LastStatusChangeAt,
	)
	return err
}

const getAvailableOperators = `-- name: GetAvailableOperators :many
SELECT os.id, os.operator_id, os.status, os.last_status_change_at
FROM operator_status os
JOIN operators o ON o.id = os.operator_id
WHERE o.tenant_id = $1 AND os.status = 'AVAILABLE'
`

func (q *Queries) GetAvailableOperators(ctx context.Context, tenantID pgtype.UUID) ([]OperatorStatus, error) {
	rows, err := q.db.Query(ctx, getAvailableOperators, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperatorStatus{}
	for rows.Next() {
		var i OperatorStatus
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.Status,
			&i.LastStatusChangeAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOperatorStatusByOperatorID = `-- name: GetOperatorStatusByOperatorID :one
SELECT id, operator_id, status, last_status_change_at FROM operator_status WHERE operator_id = $1
`

func (q *Queries) GetOperatorStatusByOperatorID(ctx context.Context, operatorID pgtype.UUID) (OperatorStatus, error) {
	row := q.db.QueryRow(ctx, getOperatorStatusByOperatorID, operatorID)
	var i OperatorStatus
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.Status,
		&i.LastStatusChangeAt,
	)
	return i, err
}

const updateOperatorStatus = `-- name: UpdateOperatorStatus :exec
UPDATE operator_status
SET status = $2,
    last_status_change_at = $3
WHERE operator_id = $1
`

type UpdateOperatorStatusParams struct {
	OperatorID         pgtype.UUID        `json:"operator_id"`
	Status             OperatorStatusType `json:"status"`
	LastStatusChangeAt pgtype.Timestamptz `json:"last_status_change_at"`
}

func (q *Queries) UpdateOperatorStatus(ctx context.Context, arg UpdateOperatorStatusParams) error {
	_, err := q.db.Exec(ctx, updateOperatorStatus, arg.OperatorID, arg.Status, arg.LastStatusChangeAt)
	return err
}
