// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :exec
INSERT INTO tenants (id, name, priority_weight_alpha, priority_weight_beta, created_at, updated_at, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateTenantParams struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	PriorityWeightAlpha pgtype.Numeric     `json:"priority_weight_alpha"`
	PriorityWeightBeta  pgtype.Numeric     `json:"priority_weight_beta"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy           pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.Exec(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.PriorityWeightAlpha,
		arg.PriorityWeightBeta,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	return err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, priority_weight_alpha, priority_weight_beta, created_at, updated_at, updated_by FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriorityWeightAlpha,
		&i.PriorityWeightBeta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getTenantByName = `-- name: GetTenantByName :one
SELECT id, name, priority_weight_alpha, priority_weight_beta, created_at, updated_at, updated_by FROM tenants WHERE name = $1
`

func (q *Queries) GetTenantByName(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByName, name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriorityWeightAlpha,
		&i.PriorityWeightBeta,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, priority_weight_alpha, priority_weight_beta, created_at, updated_at, updated_by FROM tenants ORDER BY created_at DESC
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriorityWeightAlpha,
			&i.PriorityWeightBeta,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenant = `-- name: UpdateTenant :exec
UPDATE tenants
SET name = $2,
    priority_weight_alpha = $3,
    priority_weight_beta = $4,
    updated_at = $5,
    updated_by = $6
WHERE id = $1
`

type UpdateTenantParams struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	PriorityWeightAlpha pgtype.Numeric     `json:"priority_weight_alpha"`
	PriorityWeightBeta  pgtype.Numeric     `json:"priority_weight_beta"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy           pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) error {
	_, err := q.db.Exec(ctx, updateTenant,
		arg.ID,
		arg.Name,
		arg.PriorityWeightAlpha,
		arg.PriorityWeightBeta,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	return err
}
